### ISSUE TITLE
您好，请教您一个问题

### ISSUE THREAD

**Issue by 445759814** [ch331917692/converter-file#1]
您好，请教您一个问题！为什么这里的保存路径，我设置了还是保存在了默认的目录，而且文件也是xxx.tmp

**Comment by loongwind** [comment]
你设置的路径是一个文件夹吧，没有文件名从URL中又没有获取到文件名所以默认用了tmp后缀的临时文件名，你设置保存路径的时候加上文件名应该就可以了

**Comment by loongwind** [comment]
或者你设置的保存路径是无效的 没有权限啥的

**Comment by 445759814** [comment]
权限也有，/storage/emulated/0/Android/data/com.cr.doctor/cache/cr.pdf这个就是我保存的路径

**Comment by loongwind** [comment]
看下手机里目录是不是不存在，我代码里是没有去创建目录的

**Comment by 445759814** [comment]
存在，我自己建好了目录才调下载方法的，也是按照你上面的说明一步一步写的。我看里面是反射获取的responseBody里面的路径和文件名，responseBody需要自定义吗？

**Comment by loongwind** [comment]
是的,给okHttp设置了拦截器,然后将保存路径设置到了我自定义封装的responseBody里,然后再FileConverter里使用反射获取的

**Comment by 445759814** [comment]
好的，谢谢@！
